# Generated by Django 3.0.6 on 2020-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200605_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('idade', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=20)),
                ('genMusicFav', models.CharField(max_length=255)),
            ],
        ),
    ]
